spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}/port_in_scan?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_ID}
    password: ${DB_PW}
  config:
    activate:
      on-profile: local
    import: jwt.yaml